sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t michaelferns/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true michaelferns/react-test npm test

after_success:
  - docker build -t michaelferns/fib-docker-client ./client
  - docker build -t michaelferns/fib-docker-nginx ./nginx
  - docker build -t michaelferns/fib-docker-server ./server
  - docker build -t michaelferns/fib-docker-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push michaelferns/fib-docker-client
  - docker push michaelferns/fib-docker-nginx
  - docker push michaelferns/fib-docker-server
  - docker push michaelferns/fib-docker-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: fib-docker
  env: FibDocker-env
  bucket_name: elasticbeanstalk-us-east-1-657300740104
  bucket_path: fib-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY